default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  host: localhost
  username: rails
  database: console_ulog_api_development

test:
  adapter: postgresql
  host: localhost
  username: rails
  database: console_ulog_api_test

production:
  <<: *default